# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17ODpkPIVCw5_3-MWu4SEhFs14cVcHKRW
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import warnings
warnings.filterwarnings("ignore")

#1. Load Datasets
data = pd.read_csv('/content/seasonal_agriculture_performance_dataset.csv')

data.head()

data.tail()

#2. Data Exploration & Shape
print("Rows:",data.shape[0])
print("Columns:",data.shape[1])

print("\n----- Columns Names -------")

print(data.columns)

print("\n---- Data Info ----")
print(data.info())

print("\n---- Statistical Summery ----")
print(data.describe(include='all'))

# Check Missing Value & Duplicates
print("\n------ Missing Values Before Cleaning -----")
print(data.isnull().sum())
print("Duplicate Rows:", data.duplicated().sum())

#3. Data Cleaning
data1 = data.drop_duplicates()

# Handle Missing Values for Numerical columns
numeric_cols = data1.select_dtypes(include=np.number).columns
data1[numeric_cols] = data1[numeric_cols].fillna(data1[numeric_cols].median())

# Handle Missing values fr Categorical Columns
categorical_cols = data1.select_dtypes(include='object').columns
for col in categorical_cols:
  data1[col] = data1[col].fillna(data1[col].mode()[0])

# Check Missing Value & Duplicates After Cleaning
print("\n------ Missing Values After Cleaning -----")
print(data1.isnull().sum())
print("Duplicate Rows:", data1.duplicated().sum())

#4. Seasonal Yield Analysis
season_yield = data.groupby('Season')['Yield_Tonnes_Ha'].mean()
print("\n--- Average Yield by Season ---")
print(season_yield)

plt.figure(figsize=(8,5))
sns.barplot(x=season_yield.index, y=season_yield.values, palette='viridis')
plt.title('Average Agriculture yield by Season')
plt.xlabel("Season")
plt.ylabel("Average Yield (Tonnes/Ha)")
plt.show()

#5. Total Prduction by Season
season_production = data.groupby('Season')['Production_Tonnes'].sum()
print("\n----- Total Production by Season -----")
print(season_production)


plt.figure(figsize=(8,5))
sns.barplot(x=season_production.index, y=season_production.values, palette='magma')
plt.title("Total Agriculture Production by Season")
plt.xlabel("Season")
plt.ylabel("Total Prduction(Tonnes)")
plt.show()

#6. Crop vs Season Analysis (Pivot Table & Heatnap)

crop_season = pd.pivot_table(data, values='Yield_Tonnes_Ha', index='Crop', columns='Season', aggfunc='mean')
print("\n----- Crop vs Season Pivot Tables -----")
print(crop_season)

plt.figure(figsize=(8,5))
sns.heatmap(crop_season, annot=True,fmt=".2f",cmap="YlGn")
plt.title("Average Crop Yield Across Season")
plt.show()

# 7. Environmental Conditions vs Yield Correlation
corr_cols = ['Rainfall_mm', 'Avg_Temperature_C', 'Humidity_pct', 'Yield_Tonnes_Ha']
correlation = data[corr_cols].corr()
print("\n--- Correlation Matrix ---")
print(correlation)

plt.figure(figsize=(8, 6))
sns.heatmap(correlation, annot=True, cmap='coolwarm', fmt='.2f')
plt.title("Correlation Between Environmental Factors and Yield")
plt.show()

# 8. Scatter Plots: Rainfall & Temperature vs Yield
plt.figure(figsize=(8, 5))
sns.scatterplot(data=data, x='Rainfall_mm', y='Yield_Tonnes_Ha', hue='Season', alpha=0.7)
plt.title("Rainfall vs Agricultural Yield")
plt.xlabel("Rainfall (mm)")
plt.ylabel("Yield (Tonnes/Ha)")
plt.show()


plt.figure(figsize=(8, 5))
sns.scatterplot(data=data, x='Avg_Temperature_C', y='Yield_Tonnes_Ha', hue='Season', alpha=0.7)
plt.title("Temperature vs Agricultural Yield")
plt.xlabel("Avg Temperature (°C)")
plt.ylabel("Yield (Tonnes/Ha)")
plt.show()

# 9. Resource Usage Across Seasons (Fertilizer)
fertilizer_season = data.groupby('Season')['Fertilizer_kg_ha'].mean()
print("\n--- Average Fertilizer Usage by Season ---")
print(fertilizer_season)

plt.figure(figsize=(8, 5))
sns.barplot(x=fertilizer_season.index, y=fertilizer_season.values, palette='crest')
plt.title("Average Fertilizer Usage Across Seasons")
plt.xlabel("Season")
plt.ylabel("Average Fertilizer Usage (kg/ha)")
plt.show()

# 10. Statistical Analysis (T-Test between Kharif and Rabi Yields)
season1 = data[data['Season'] == 'Kharif']['Yield_Tonnes_Ha']
season2 = data[data['Season'] == 'Rabi']['Yield_Tonnes_Ha']
t_stat, p_value = stats.ttest_ind(season1, season2, equal_var=False)
print("\n--- T-Test Results (Kharif vs Rabi Yields) ---")
print("T-statistic:", t_stat)
print("P-value:", p_value)

if p_value < 0.05:
    print("Result: The difference in yield between Kharif and Rabi is statistically significant.")
else:
    print("Result: The difference in yield between Kharif and Rabi is not statistically significant.")

# 11. Outlier Detection (Boxplot)
plt.figure(figsize=(8, 5))
sns.boxplot(data=data, x='Season', y='Yield_Tonnes_Ha', palette='Set2')
plt.title("Yield Distribution and Outliers Across Seasons")
plt.xlabel("Season")
plt.ylabel("Yield (Tonnes/Ha)")
plt.show()

# 12. Final Summary Table
summary_of_data = data.groupby('Season').agg({
    'Yield_Tonnes_Ha': 'mean',
    'Production_Tonnes': 'sum',
    'Rainfall_mm': 'mean',
    'Avg_Temperature_C': 'mean'
}).reset_index()

print("\n--- Final Summary Table ---")
print(summary_of_data)